### ISSUE TITLE
HunkBlame broken

### ISSUE THREAD

**Issue by linzhp** [SoftwareIntrospectionLab/MininGit#149]
It says:

Error in importing extension HunkBlame: cannot import name NemerleLexer
Invalid extension HunkBlame

I tried installing Pygments, both from apt-get and easy_install, still not working. The error originated from line_types.py: 

``` python
from pygments.lexers import NemerleLexer
```

So I wonder: @apepper, which version of Pygments were you using?

**Comment by apepper** [comment]
I installed pygments from the development repository, which can be found at https://bitbucket.org/birkenfeld/pygments-main .
This is a mecurial-repo, so in order to fetch it with git you need git-hg which can be found at http://offbytwo.com/git-hg/ .

If you want to, you can revert the commit 900a320ffb097413aff6fb53d8123add8023f7ee . I made this commit, because there is a bug with nemerle files in Pygments which I reported at https://bitbucket.org/birkenfeld/pygments-main/issue/706/nemerle-lexer-ends-in-an-infinite-loop . Most of the time, this should not be a problem.

**Comment by apepper** [comment]
sorry, wrong button.

**Comment by linzhp** [comment]
Alright, the development version works. I would close this for now
