### ISSUE TITLE
old_start_line and old_end_line in some hunks are not correct

### ISSUE THREAD

**Issue by linzhp** [SoftwareIntrospectionLab/MininGit#26]
This bug causes HunkBlame to throws away some hunks. Steps to reproduce this bug:
1. Run HunkBlame in debug mode and redirect the command line output to a voldemort.log 
2. grep '0 bug commits' voldemort.log, this will find all hunks with 0 bug commit. These hunks are problematic
3. select these hunks from hunks table, get their old_start_line and old_end_line
4. Search each line in the grep output of step 2 in voldemort.log, not far before the searched line, you will find a git-blame command, which runs against the previous revision of the hunk
5. Manually run the git-blame again, you will find the total lines of the file is less than old_start_line and old_end_line

**Comment by cflewis** [comment]
I had a feeling that the Hunks algorithm was going to return!

I tried doing it replicating as close to the original algorithm as possible, but I felt a bug was likely.

Thank you for the reproduction steps. I will have a look as soon as I can.

**Comment by cflewis** [comment]
Hi Zhongpeng,
Good news and bad news!

Good news: I can replicate
Bad news: I think this is a problem with git

Look at hunk ID 11428 (file_id 636, commit_id 785, `StorageService.java`). The patch for this went in at [this commit](https://github.com/voldemort/voldemort/blob/4fc16f475e290d02e507ce74de07c6b949d429a7/src/java/voldemort/server/storage/StorageService.java), and here is the [previous one](https://github.com/voldemort/voldemort/blob/e5bdbcc6ded87d4a54b304d7408e91b7d3f9efa9/src/java/voldemort/server/storage/StorageService.java).

The hunk details are: old_start_line/old_end_line: 344, new_start_line/new_end_line: 340. The old_start_line/old_end_line should be 324. The new ones are right.

Unfortunately, it gets worse.

The patch for this reads: 

```
@@ -341,7 +337,7 @@ public class StorageService extends AbstractService {
             throw new VoldemortException(lastException);
    }

-    public VoldemortMetadata getMetadataStore() {
+    public MetadataStore getMetadataStore() {
         return this.metadata;
    }
```

Going by [how to read a unified diff](http://www.markusbe.com/2009/12/how-to-read-a-patch-or-diff-and-understand-its-structure-to-apply-it-manually/#how-to-read-a-unified-diff) this means Git is saying that the patch starts at Line 341 in the old file, which is wrong. It should start at 321.

`git blame` is returning the old file correctly, but because the patch incorrectly reports the final line, it doesn't work (sanity check: you do want to get the blame for the old file, not the new file, right?)

I'm not sure how to continue. When you look at the [patch in GitHub](https://github.com/voldemort/voldemort/commit/4fc16f475e290d02e507ce74de07c6b949d429a7#diff-13), they have the same problem, the old lines are wrong and report that the change was at 344 as well.

Git is telling us the wrong thing. Without us rewriting Git, or adding lots of logic to try and fix these, I don't think there is anything we can do. I'm inclined to WishList this bug and just deal with what we have, especially because GitHub is also failing. If you are more concerned that we need to do something, let me know and we'll talk.

**Comment by linzhp** [comment]
Yes, blaming the old file is what I need.

This issue doesn't happen too overwhelming; we could just leave it as it is: let HunkBlame throws away those hunks. I don't think rewriting Git is a trivial job nor relevant to our research. However, it would be better to let developers of Git or GitHub notified about this issue. That's what we could do about this issue, in my opinion.

**Comment by cflewis** [comment]
Yes, notifying the Git dev team would be handy, but Git doesn't have a bug ticket system, so without signing up for mailing lists and stuff, we aren't going to be able to notify them (nor find out if they are already aware) :(

**Comment by cflewis** [comment]
Hi Zhongpeng,
Looked harder into this one, spoke with some guys on the #git IRC channel.

Turns out there isn't a problem with Git, but more the way we're looking at it. Unfortunately, Voldemort uses a lot of feature branching. While GitHub (and Git, to some extent) flattens those branches into a linear timeline, each file really exists in multiple states at any one time. There are many, many commits between the two we're looking at, and each author didn't merge with one another. They were on different branches. If I am looking at it right, the diff file is correct, but only for the state that the file was in for the person _on their branch_. So there are multiple copies of the file, but we're only looking at one and thinking of it as only existing as one.

So, git isn't wrong, but there's nothing we can do about it either, unfortunately.
