### ISSUE TITLE
Wishlist: Progess Indication

### ISSUE THREAD

**Issue by philip-iii** [SoftwareIntrospectionLab/MininGit#38]
This is more of a minor quirk, and I realize that usually cvsanaly is run in a batch process, but it would be nice to have optional progress indication, especially with extensions that tend to take hours and days to complete to have at least some way of estimating when a task is expected to complete. 

I've been hacking in improvised indicators occasionally here and there in cases where errors and crashes occurred or when testing out some workloads, but I think this should be taken into consideration as an overall design concept. It shouldn't produce large volumes of information, but rather just a minimal indication of e.g. the workload currently being processed and the number of entries processed so far out of the total numbers of entries.

**Comment by cflewis** [comment]
With the reliability of the extensions we're working on being somewhat flaky, we're currently using everything in debug mode, and then guessing percentages. However, we've been fairly bad at this: a process I guessed would finish in a couple of days ended up taking a week.

This feature should probably update a number of which commit it is up to, and ideally it would do that with something nice like ncurses, so as not to fill up the screen.

**Comment by cflewis** [comment]
Looks like Clint will do exactly what we need:

https://github.com/kennethreitz/clint

**Comment by apepper** [comment]
I did some work on this. You can see it on pull request #138. I'm using the library http://code.google.com/p/python-progressbar/

# Usage

Import package Progress in your header:

```
from Progress import Progress
```

Initialise it with a string and a maximum numbers of steps:

```
progress = Progress("[Extension Patches]", max_steps)
```

For each step done you need to call the following:

```
progress.finished_one()
```

After all is done, just do this:

```
progress.done()
```

# Example Output:

```
[Extension CommitsLOC]: 100% ||||||||||||||||||||||||||||||||||||||||||||||||||||| Time: 0:00:45
```

# Currently working

I also tried to add this to CVSAnalY Core, but since it's quite complicated and I didn't wanted to break the architecture I didn't added so far. But at least the following extensions are working:
- Patches
- PatchLOC
- CommitsLOC (sort of)
- Hunks
- HunkBlame
- BugFixMessage

Feedback is welcomed!

**Comment by philip-iii** [comment]
Thanks a lot for this Alex! I've only tried it on a smaller repo, but so far it does a fine job (though it does get a little distorted when there are other messages popping up in between, no surprise there). I'd say it is fairly sufficient.
