### ISSUE TITLE
Verify Content works if the Content table is already full

### ISSUE THREAD

**Issue by cflewis** [SoftwareIntrospectionLab/MininGit#60]
Content looks like its going into an infinite loop if the Content table is already full.

Verify (and fix, if necessary):
1. Does Content go into an infinite loop is partly full?
2. Does Content go into an infinite loop if completely full?

If neither, flag as unreproducible and won't fix.

Check this output:
http://eisbox.soe.ucsc.edu/jenkins/job/cvsanaly/40/console

Debugs were put in to show what it was doing in the loop, last thing it did was continue due to content already being in there then an SQL statement which returns (according to the DB), but Content just hangs.

**Comment by linzhp** [comment]
What did yo mean by "full"? Reach the space limit hard drive?

**Comment by cflewis** [comment]
"Full" as in it has all the records in it already. Sorry, it wasn't clear :)

**Comment by linzhp** [comment]
I ran Content using V8 data on my laptop, both in partly full and completely full situation, it worked fine. In addition, I looked at the console output of Jenkins, it didn't seem to me to be a infinite loop, because the main loop of Content was still iterating through FileRev, and making the latter running out of current data in hand and fetching next 1000 records. How long it took in such loop on Jenkins? On my laptop, even in completely full situation, it only took a few minutes to run through. I believe V8 to be larger than voldemort, so it shouldn't take too much time on Jenkins.

**Comment by cflewis** [comment]
In Jenkins, it was hitting four hours, before I was aborting it. It should only take about one hour.

As we can't reproduce it, I'll close this as a Won't Fix, but we should keep our eye on it.

**Comment by cflewis** [comment]
Closing.

**Comment by linzhp** [comment]
When I ran it on my laptop, it also took four hours when running V8 data from scratch, with 23,818 records inserted. It started up quickly, but after an hour, it became very slow. Reason unknown.
