### ISSUE TITLE
Bug: CVSAnalY breaks when no branch is given

### ISSUE THREAD

**Issue by apepper** [SoftwareIntrospectionLab/MininGit#96]
When no branch is specified all local brunches should be used. But instead cvsanaly breaks terribly:

```
$ cvsanaly2 .
Parsing log for /repo_path (git)
Traceback (most recent call last):
  File "/usr/local/bin/cvsanaly2", line 5, in <module>
    pkg_resources.run_script('cvsanaly==2.3.1', 'cvsanaly2')
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/pkg_resources.py", line 442, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/pkg_resources.py", line 1160, in run_script
    execfile(script_filename, namespace, namespace)
  File "/Library/Python/2.6/site-packages/cvsanaly-2.3.1-py2.6.egg/EGG-INFO/scripts/cvsanaly2", line 37, in <module>
    retval = pycvsanaly2.main.main (sys.argv[1:])
  File "/Library/Python/2.6/site-packages/cvsanaly-2.3.1-py2.6.egg/pycvsanaly2/main.py", line 473, in main
    _parse_log(path or uri, repo, parser, reader, config, db)
  File "/Library/Python/2.6/site-packages/cvsanaly-2.3.1-py2.6.egg/pycvsanaly2/main.py", line 142, in _parse_log
    reader.start(new_line, (parser, writer))
  File "/Library/Python/2.6/site-packages/cvsanaly-2.3.1-py2.6.egg/pycvsanaly2/Log.py", line 98, in start
    self._read_from_repository(new_line_cb, user_data)
  File "/Library/Python/2.6/site-packages/cvsanaly-2.3.1-py2.6.egg/pycvsanaly2/Log.py", line 84, in _read_from_repository
    new_line_cb(line, user_data)
  File "/Library/Python/2.6/site-packages/cvsanaly-2.3.1-py2.6.egg/pycvsanaly2/main.py", line 134, in new_line
    parser.feed(line)
  File "/Library/Python/2.6/site-packages/cvsanaly-2.3.1-py2.6.egg/pycvsanaly2/Parser.py", line 57, in feed
    self._parse_line(line)
  File "/Library/Python/2.6/site-packages/cvsanaly-2.3.1-py2.6.egg/pycvsanaly2/GitParser.py", line 249, in _parse_line
    self.branch.set_tail(git_commit)
AttributeError: 'NoneType' object has no attribute 'set_tail'
```

Any idea how to fix this?

**Comment by cflewis** [comment]
We've never used it with or without branches, we always use it with whatever is currently checked out (usually always master), so have never come across this.

Unfortunately, fixing this would require a pretty strong knowledge of both the parser and Git's storage structure. Because we don't use this in the way you describe, we can't dedicate any time to fixing it :(

Could you not make a quick wrapper script which asks Git for the different branch names, then run cvsanaly with each branch, then run the extensions you want using the `-n` flag? It isn't pretty, but it should run fairly quickly.

**Comment by apepper** [comment]
Running from one problem into the next one: One thing I notice: `cvsanaly2 --branch="branchname" .` doesn't have any effect on the calculation. Only the current branch is used. So if branch "foo" is checked out, only this branch is used NOT what is given in --branch=.

My workarount script:

```
#!/bin/bash
for b in 'branch1' 'branch2' 'branch3'
do
  git checkout $b
  cvsanaly2 --branch="$b" .
done
```

**Comment by cflewis** [comment]
Hmm.

The `--branch` flag is something you added ;) Do you think its fixable, or do you think we need to revert those changes?

**Comment by apepper** [comment]
I did not add the `--branch` flag. In fact you added the `--branch` flag (see c499c0b1d38c1794719f8dde9540627841322999) and feature (see 9a446d64ac716108fcc989eb6078eb3d576119af). All I did was documenting, who to use it for local and remote branches (see 84df5123ca30ab109f70d88202df76171e2e6516). 

I'm not really sure how to fix this, otherwise I would already have done so.

**Comment by cflewis** [comment]
Oh. Hmm. I remember now (I've worked too long on this project...)

This did used to work. I know it did, I verified it. I remember testing it now. Either we made a change that broke it, or Git made a change that broke it (could easily be either). I never tested it for the all local branches behavior that you described, it was always designed so that you offered a branch. We never ended up using it, though, and just stuck with master.

I'm not currently working on the Git parser. @linzhp , do you think you'll need this to be working for your work, or should we disable it for now?

**Comment by cflewis** [comment]
Pinging @linzhp again.

**Comment by linzhp** [comment]
Sorry, I missed this message before. I've never used --branch, and don't think I will need this in near future. So disabling it would be a good solution. We could always checkout the branch we are interested first and run cvsanaly on it.

**Comment by cflewis** [comment]
Alright, looks like the right thing to do here is remove the references to the branch option in `main.py`, then hope it's a Git thing and it will work again later.

**Comment by philip-iii** [comment]
Hold on a bit with this one. Although, I did not have the originally mentioned issues (must have been fixed since?), a few observations I'd like to mention (it does get off-topic, maybe a new issue or a request for clarification should be issued):

As it would seem at the moment, this has (indirect) implications on the hunk file_id assignment (potentially related to #79). 

As it is at the moment, when no branch is specified, the latest file_id for a given file path (from ALL branches) is used for all subsequent hunks (even if they are not on the same branch as the one the latest file_id for the file path in question was derived from). This leads to rather bizarre results and the solution at the moment is to process all branches individually (which seems to require that all branches are stored in separate databases, not to mention all the mixing and matching afterward). Although, the results appear to be better with individual branches, I still have to figure out what to make out of the differences to previous results on the same data set.

Am I misunderstanding something, is this the expected behavior?

**Comment by apepper** [comment]
@philip-iii: That's correct: currently the file-path-resolution only takes the last commit id into account. So do different parallel branches which both work with the same file set (move and renaming) could yield to wrong file-paths for a given file_id.

One quickfix would be, to always save the current file_path for a given file_id and commit_id, if the file is modified. Until now, only newly created, renamed or moved files are stored to file_paths. This would make it essentially as big as the actions table. But still quick a waste of space. On the other hand file_path resolution should then always yield correct results, especially when used together with different branches.

**Comment by philip-iii** [comment]
@apepper: Well, I think at least the file_ids in the actions data and in the hunks data shall be consistent with regard to this. Out of the top of my head, perhaps checking against the actions table when assigning file_ids to hunks will be an option (assuming that the data in the actions table is correct that is), especially when there are several candidate file_ids. No idea how much more or less effort would this require.

**Comment by cflewis** [comment]
This conversation is somewhat moot in that branch resolution in cvsanaly for Git is broken to the point of unfixable. We had a discussion about this on the mailing list. Git does not/cannot tell you where a commit came from. It exists on multiple branches at any given time, and it doesn't keep any history about which branch a commit was created in (which is probably what you want to know).

The Git parser basically makes a guess, and the guess is frequently wrong. For example, on our test database, a commit I know must have been entered on the master branch (as its the initial commit) is flagged as being on a feature branch. This is clearly wrong, but there is no obvious means of fixing this.

This is why this feature was introduced, and I believed was working at some point (otherwise I wouldn't have merged and closed the original tracking issue). I don't have time to test or replicate (I'm full-time on a cvsanaly-based project, but it doesn't use Git), so I am relying on those who are using it to report issues and find workarounds.

As far as file paths not working for branches in other repositories that might have detectable branching, such as SVN,  support for other parsers is maintained by SIL on a best effort basis, as we personally have no need for mining things across the network (we'd always use `svn2git` if we had to go at an SVN repo). I'm not going to stop a useful patch going in because it doesn't have non-Git support.

I would note that modifying hunks to have a different SQL query will increase mining time (which @apepper managed to dramatically drop with the file_paths extension), as Hunks takes a disproportionate amount of time due to the number of records it inserts. I would prefer @apepper's solution. File paths should now have some fairly paranoid indexes on it, so most queries will return quickly even if there are a large number of records (provided your machine has enough memory to store the index).

**Comment by mfenner1** [comment]
So, I checked out the most recent versions of the code as of July 11 (repo handler 3.4; cvsanaly 2.4 according to the setup.py files).  [incidentally, cvsanaly/setup.py has a typo or mismatch in repo-handler versions:  both 3.4 and 3.5 show up]

Running: % cvsanaly2 --db-driver sqlite -d ../tmpdb/vold2.db

I get the same error message as @apepper.  I'm curious how if it is working now, if there is something broken between mysql/sqlite, or another possibility ...

**Comment by cflewis** [comment]
I'm afraid I can't help (my employment continues through to mid-September). If I could assign this to @apepper, I would :)

@linzhp may have some free cycles to take a look at this (I have no idea what his schedule is right now), as it seems to be affecting multiple people.

However, as always, the quickest way to resolution is a pull request ;)

**Comment by mfenner1** [comment]
No worries!  I definitely understand "best-effort" and "prior commitments"!  If I can make any headway, I'll definitely submit a patch.

**Comment by apepper** [comment]
I had a closer look inside. I see two different issues:
1. The file_paths with different branches
2. Why cvsanaly fails, if no branch is given.

The first issue can be fixed quite easy, as discussed before. For this, all that is needed is to replace in DBContentHandler.py this:

```
elif action.type == 'M':
  # A file has been modified
  file_id = self.__get_file_for_path(path, log.id)[0]
```

with:

```
elif action.type == 'M':
  # A file has been modified
  file_id = self.__get_file_for_path(path, log.id)[0]
  # Save also file_path
  self.__add_file_path(log.id, file_id, path) ##The is the actual fix.
```

I haven't added to the patch, because in my tests the file_paths table grew from 5292 to 7931, while the hunk table yielded the same results. So would not add this, only if studying a project, where a lot of (paralel) renaming takes place. If this is needed, please open another issue, because it's quite a different thing.

For the second I already made a pull request. If having more than one remote, and the remote that is not "origin" contained the most recent commit, cvsanaly failed. I adjusted the regex to better match remotes. With my tests, cvsanaly now could run without having to specify a branch. So for me, this closes the issue.
